### ISSUE TITLE
Request: Installer tutorial

### ISSUE THREAD

**Issue by testmad** [crilleengvall/electron-tutorial-app#1]
Awesome set of current tutorials.  Any chance on getting a tut for doing installers for all 3 platforms?

**Comment by crilleengvall** [comment]
installer tutorial is on the todo-list. I don't have an ETA but i'll take a look at it as soon as possible.

**Comment by crilleengvall** [comment]
macOS dmg tutorial is published: http://www.christianengvall.se/dmg-installer-electron-app/
Windows and Linux tutorial is on its way

**Comment by crilleengvall** [comment]
Windows tutorial added: http://www.christianengvall.se/electron-windows-installer/

**Comment by crilleengvall** [comment]
And finally a debian-package tutorial added: https://www.christianengvall.se/electron-installer-debian-package/
