### ISSUE TITLE
Any way to create an installer like .pkg for windows?

### ISSUE THREAD

**Issue by AhadCove** [crilleengvall/electron-tutorial-app#16]
Thank you so much for this tutorial, I am a little confused though. I made the installer and everything, but when I run it all it does is open my app for a few seconds and reopens.
I was looking to just get a way to make an installer (like .pkg does) and Sign the installer so I can submit to windows store. I just wanted the installer to install to program files and create a shortcut on the desktop, is this possible?

**Comment by crilleengvall** [comment]
Hi Ahad!

I added an answer to this in the comment sections of the tutorial: http://disq.us/p/1f5iiil
