### ISSUE TITLE
There is an ERROR for package-win

### ISSUE THREAD

**Issue by ue** [crilleengvall/electron-tutorial-app#21]
I got this error after run `sudo npm run package-win` 
also I tried `package-mac` worked correct.

<img width="562" alt="screen shot 2017-11-04 at 01 27 20" src="https://user-images.githubusercontent.com/9980498/32398275-011f3a4a-c0f7-11e7-8f88-785b54a4004f.png">

**Comment by crilleengvall** [comment]
Hi!

You need to install wine to build package an electron app on macOS. You can read more here:
https://github.com/electron-userland/electron-packager#building-windows-apps-from-non-windows-platforms

**Comment by ue** [comment]
Hi. I installed the wine. But still i got same error.

<img width="507" alt="screen shot 2017-11-04 at 12 22 02" src="https://user-images.githubusercontent.com/9980498/32404115-8a652066-c152-11e7-9a07-e79b337099cd.png">

<img width="572" alt="screen shot 2017-11-04 at 12 22 14" src="https://user-images.githubusercontent.com/9980498/32404117-8e7c0fde-c152-11e7-886a-bc4ca45645c8.png">

**Comment by crilleengvall** [comment]
the error message now is "wine is not owned by you"
i'm not familiar with running wine unfortunately. when googling that error message it seems you need to set some kind of permission.
